services:
  postgres:
    image: postgres:16-alpine
    container_name: ktor-sample-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
